from PyQt5 import QtCore, QtGui, QtWidgets

class Window_UI(object):
    def designer(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1250, 800)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.centralwidget.setFont(font)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        font.setFamily("Arial")
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.splitter.setFont(font)
        self.splitter.setFrameShape(QtWidgets.QFrame.StyledPanel)  # 修改为StyledPanel可以为Splitter添加一些样式
        self.splitter.setFrameShadow(QtWidgets.QFrame.Raised)  # 设置阴影效果
        self.splitter.setMidLineWidth(1)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setOpaqueResize(True)
        self.splitter.setHandleWidth(15)
        self.splitter.setChildrenCollapsible(True)
        self.splitter.setObjectName("splitter")
        self.table_wrapper = QtWidgets.QWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding,
                                           QtWidgets.QSizePolicy.Expanding)  # 修改为Expanding以使组件能够更好地填充空间
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table_wrapper.sizePolicy().hasHeightForWidth())
        self.table_wrapper.setSizePolicy(sizePolicy)
        font.setFamily("Arial")
        self.table_wrapper.setFont(font)
        self.table_wrapper.setObjectName("table_wrapper")
        self.gridLayout = QtWidgets.QGridLayout(self.table_wrapper)
        self.gridLayout.setContentsMargins(10, 10, 10, 10)  # 添加一些边距
        self.gridLayout.setObjectName("gridLayout")
        self.if_box = QtWidgets.QComboBox(self.table_wrapper)
        self.if_box.setMinimumSize(QtCore.QSize(150, 30))  # 调整大小
        self.if_box.setMaximumSize(QtCore.QSize(250, 16777215))
        self.if_box.setFont(font)
        self.if_box.setObjectName("if_box")
        self.if_box.addItem("")
        self.gridLayout.addWidget(self.if_box, 0, 0, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.table_wrapper)
        self.widget_2.setFont(font)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout.addWidget(self.widget_2, 0, 2, 1, 1)
        self.search_text = QtWidgets.QLineEdit(self.table_wrapper)
        self.search_text.setMinimumSize(QtCore.QSize(150, 30))  # 调整大小
        self.search_text.setFont(font)
        self.search_text.setObjectName("search_text")
        self.gridLayout.addWidget(self.search_text, 2, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        self.search_button = QtWidgets.QPushButton(self.table_wrapper)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_button.sizePolicy().hasHeightForWidth())
        self.search_button.setSizePolicy(sizePolicy)
        self.search_button.setMinimumSize(QtCore.QSize(80, 30))  # 调整大小
        font.setPointSize(10)
        self.search_button.setFont(font)
        self.search_button.setObjectName("search_button")
        self.gridLayout.addWidget(self.search_button, 2, 1, 1, 1)
        self.table = QtWidgets.QTableWidget(self.table_wrapper)
        font.setFamily("Arial")
        self.table.setFont(font)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.table.setFont(font)
        self.table.setMidLineWidth(2)
        self.table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.table.setRowCount(0)
        self.table.setObjectName("table")
        self.table.setColumnCount(7)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(6, item)
        self.table.horizontalHeader().setVisible(True)
        self.table.horizontalHeader().setDefaultSectionSize(100)
        self.table.horizontalHeader().setMinimumSectionSize(50)
        self.table.horizontalHeader().setSortIndicatorShown(False)
        self.table.horizontalHeader().setStretchLastSection(True)  # 修改为True以使最后一列填充剩余空间
        self.table.verticalHeader().setVisible(False)
        self.gridLayout.addWidget(self.table, 3, 0, 1, 3)
        self.tab_wrapper = QtWidgets.QWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_wrapper.sizePolicy().hasHeightForWidth())
        self.tab_wrapper.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.tab_wrapper.setFont(font)
        self.tab_wrapper.setObjectName("tab_wrapper")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_wrapper)
        self.gridLayout_2.setContentsMargins(5, 5, 5, 5)  # 添加一些边距以改善布局
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tab = QtWidgets.QTabWidget(self.tab_wrapper)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.tab.setFont(font)
        self.tab.setStyleSheet("QTabWidget::pane\n"
                               "\n"
                               "{\n"
                               "\n"
                               "border-width: 2px;\n"  # 将边框宽度修改为2px
                               "\n"
                               "border-color:#2d2d2d;\n"  # 修改边框颜色为深灰色
                               "\n"
                               "border-style:outset;\n"
                               "\n"
                               "border-radius: 3px;\n"
                               "\n"
                               "background-color: rgb(230, 230, 230);\n"  # 修改背景颜色为浅灰色
                               "\n"
                               "}\n"
                               "")
        self.tab.setIconSize(QtCore.QSize(20, 20))
        self.tab.setElideMode(QtCore.Qt.ElideNone)
        self.tab.setDocumentMode(False)
        self.tab.setTabsClosable(False)
        self.tab.setMovable(False)
        self.tab.setTabBarAutoHide(False)
        self.tab.setObjectName("tab")
        self.detail = QtWidgets.QWidget()
        self.detail.setMinimumSize(QtCore.QSize(0, 0))
        self.detail.setObjectName("detail")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.detail)
        self.gridLayout_3.setContentsMargins(10, 10, 10, 10)  # 添加一些边距以改善布局
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.detail_tree = QtWidgets.QTreeWidget(self.detail)
        self.detail_tree.setAutoExpandDelay(-1)
        self.detail_tree.setObjectName("detail_tree")
        self.detail_tree.header().setDefaultSectionSize(200)
        self.detail_tree.header().setMinimumSectionSize(200)
        self.gridLayout_3.addWidget(self.detail_tree, 0, 0, 1, 1)
        self.tab.addTab(self.detail, "")
        self.hex_info = QtWidgets.QWidget()
        self.hex_info.setObjectName("hex_info")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.hex_info)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.hex_text = QtWidgets.QTextBrowser(self.hex_info)
        font = QtGui.QFont()
        font.setFamily("Courier New")  # 修改字体为Courier New
        font.setPointSize(10)
        self.hex_text.setFont(font)
        self.hex_text.setStyleSheet(
            "background-color: #f0f0f0;"  # 设置背景色为浅灰色
            "color: #333;"  # 设置文字颜色为深灰色
            "border: 1px solid #ccc;"  # 设置边框
            "padding: 5px;"  # 设置内边距
        )
        self.hex_text.setObjectName("hex_text")
        self.verticalLayout_2.addWidget(self.hex_text)
        self.tab.addTab(self.hex_info, "")
        self.gridLayout_2.addWidget(self.tab, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        font.setFamily("Arial")
        self.hex_text.setFont(font)
        self.hex_text.setObjectName("hex_text")
        self.verticalLayout_2.addWidget(self.hex_text)
        self.tab.addTab(self.hex_info, "")
        font = QtGui.QFont()
        font.setFamily("Arial")
        font = QtGui.QFont()
        font.setFamily("Arial")
        item_font = QtGui.QFont()
        item_font.setFamily("Arial")
        item_font.setPointSize(10)  # 设置字体大小为10
        for column in range(6):
            item = QtWidgets.QTableWidgetItem()
            item.setFont(item_font)

        font = QtGui.QFont()
        font.setPointSize(12)
        self.gridLayout_2.addWidget(self.tab, 1, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1105, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.menubar.setFont(font)
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.menu.setFont(font)
        self.menu.setObjectName("menu")
        self.menu_C = QtWidgets.QMenu(self.menubar)
        self.menu_C.setObjectName("menu_C")
        MainWindow.setMenuBar(self.menubar)
        self.action_start = QtWidgets.QAction(MainWindow)
        self.action_start.setCheckable(False)
        self.action_start.setObjectName("action_start")
        self.action_about_sniffer = QtWidgets.QAction(MainWindow)
        self.action_about_sniffer.setObjectName("action_about_sniffer")
        self.action_stop = QtWidgets.QAction(MainWindow)
        self.action_stop.setObjectName("action_stop")
        self.action_restart = QtWidgets.QAction(MainWindow)
        self.action_restart.setObjectName("action_restart")
        self.action_clean_all = QtWidgets.QAction(MainWindow)
        self.action_clean_all.setObjectName("action_clean_all")
        self.action_open_file = QtWidgets.QAction(MainWindow)
        self.action_open_file.setEnabled(True)
        self.action_open_file.setObjectName("action_open_file")
        self.action_save_as = QtWidgets.QAction(MainWindow)
        self.action_save_as.setObjectName("action_save_as")
        self.action_show_details = QtWidgets.QAction(MainWindow)
        self.action_show_details.setObjectName("action_show_details")
        self.action_reassemble = QtWidgets.QAction(MainWindow)
        self.action_reassemble.setObjectName("action_reassemble")
        self.action_tcp_to_file = QtWidgets.QAction(MainWindow)
        self.action_tcp_to_file.setObjectName("action_tcp_to_file")
        self.action_exit = QtWidgets.QAction(MainWindow)
        self.action_exit.setPriority(QtWidgets.QAction.NormalPriority)
        self.action_exit.setObjectName("action_exit")
        self.menu.addAction(self.action_open_file)
        self.menu.addAction(self.action_save_as)
        self.menu.addSeparator()
        self.menu.addAction(self.action_exit)
        self.menu_C.addAction(self.action_start)
        self.menu_C.addAction(self.action_stop)
        self.menu_C.addAction(self.action_restart)
        self.menu_C.addAction(self.action_clean_all)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_C.menuAction())
        self.name(MainWindow)
        self.tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.table.setColumnWidth(5, 100)
        self.table.resizeColumnToContents(5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        self.table.setFont(font)
        horizontalHeader = self.table.horizontalHeader()
        horizontalHeader.setFont(font)


    def name(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.if_box.setCurrentText(_translate("MainWindow", "选择网卡"))
        self.if_box.setItemText(0, _translate("MainWindow", "选择网卡"))
        self.search_text.setPlaceholderText(_translate("MainWindow", "协议类型"))
        self.search_button.setText(_translate("MainWindow", "搜索"))
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "No."))
        item = self.table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Time"))
        item = self.table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Source"))
        item = self.table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Destination"))
        item = self.table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Protocol"))
        item = self.table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Length"))
        item = self.table.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Information"))
        self.detail_tree.headerItem().setText(0, _translate("MainWindow", "字段"))
        self.detail_tree.headerItem().setText(1, _translate("MainWindow", "值"))
        self.tab.setTabText(self.tab.indexOf(self.detail), _translate("MainWindow", "详细信息"))
        self.hex_text.setHtml(_translate("MainWindow",
                                         """<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
                                         <html>
                                             <head>
                                                 <meta name="qrichtext" content="1" />
                                                 <style type="text/css">
                                                     p, li { white-space: pre-wrap; font-family:'Courier New'; font-size:12pt; }
                                                 </style>
                                             </head>
                                             <body>
                                                 <p style="-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">
                                                     <br />
                                                 </p>
                                             </body>
                                         </html>"""))

        self.tab.setTabText(self.tab.indexOf(self.hex_info), _translate("MainWindow", "HEX"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.menu_C.setTitle(_translate("MainWindow", "捕获"))
        self.action_start.setText(_translate("MainWindow", "开始捕获"))
        self.action_start.setShortcut(_translate("MainWindow", "Ctrl+E"))
        self.action_about_sniffer.setText(_translate("MainWindow", "关于sniffer"))
        self.action_stop.setText(_translate("MainWindow", "停止捕获"))
        self.action_stop.setShortcut(_translate("MainWindow", "Ctrl+F"))
        self.action_restart.setText(_translate("MainWindow", "重新开始"))
        self.action_restart.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.action_clean_all.setText(_translate("MainWindow", "清除全部"))
        self.action_clean_all.setToolTip(_translate("MainWindow", "清除全部"))
        self.action_clean_all.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.action_open_file.setText(_translate("MainWindow", "打开文件"))
        self.action_open_file.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.action_save_as.setText(_translate("MainWindow", "保存"))
        # self.action_save_as.setToolTip(_translate("MainWindow", "另存为..."))
        self.action_save_as.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.action_exit.setText(_translate("MainWindow", "退出"))
        self.action_exit.setShortcut(_translate("MainWindow", "Ctrl+Q"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Window_UI()
    ui.designer(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

